const provinces = [
    { id: "phnom-penh", province_name: "Phnom Penh", nameKh: "ភ្នំពេញ", city: "Phnom Penh", country: "Cambodia", latitude: 11.5564, longitude: 104.9282 },
    { id: "kampong-cham", province_name: "Kampong Cham", nameKh: "កំពង់ចាម", city: "Kampong Cham", country: "Cambodia", latitude: 11.9934, longitude: 105.4635 },
    { id: "siem-reap", province_name: "Siem Reap", nameKh: "សៀមរាប", city: "Siem Reap", country: "Cambodia", latitude: 13.3618, longitude: 103.8606 },
    { id: "battambang", province_name: "Battambang", nameKh: "បាត់ដំបង", city: "Battambang", country: "Cambodia", latitude: 13.0957, longitude: 103.2022 },
    { id: "kandal", province_name: "Kandal", nameKh: "កណ្តាល", city: "Ta Khmau", country: "Cambodia", latitude: 11.4833, longitude: 104.9500 },
    { id: "kampot", province_name: "Kampot", nameKh: "កំពត", city: "Kampot", country: "Cambodia", latitude: 10.6104, longitude: 104.1814 },
    { id: "sihanoukville", province_name: "Sihanoukville", nameKh: "ព្រះសីហនុ", city: "Sihanoukville", country: "Cambodia", latitude: 10.6253, longitude: 103.5234 },
    { id: "kampong-thom", province_name: "Kampong Thom", nameKh: "កំពង់ធំ", city: "Stueng Saen", country: "Cambodia", latitude: 12.7111, longitude: 104.8887 },
    { id: "prey-veng", province_name: "Prey Veng", nameKh: "ព្រៃវែង", city: "Prey Veng", country: "Cambodia", latitude: 11.4868, longitude: 105.3253 },
    { id: "takeo", province_name: "Takeo", nameKh: "តាកែវ", city: "Doun Kaev", country: "Cambodia", latitude: 10.9908, longitude: 104.7846 },
    { id: "svay-rieng", province_name: "Svay Rieng", nameKh: "ស្វាយរៀង", city: "Svay Rieng", country: "Cambodia", latitude: 11.0878, longitude: 105.7992 },
    { id: "kampong-speu", province_name: "Kampong Speu", nameKh: "កំពង់ស្ពឺ", city: "Chbar Mon", country: "Cambodia", latitude: 11.4531, longitude: 104.5208 },
    { id: "koh-kong", province_name: "Koh Kong", nameKh: "កោះកុង", city: "Khemarak Phoumin", country: "Cambodia", latitude: 11.6153, longitude: 102.9838 },
    { id: "stung-treng", province_name: "Stung Treng", nameKh: "ស្ទឹងត្រែង", city: "Stung Treng", country: "Cambodia", latitude: 13.5259, longitude: 105.9740 },
    { id: "ratanakiri", province_name: "Ratanakiri", nameKh: "រតនគិរី", city: "Banlung", country: "Cambodia", latitude: 13.7397, longitude: 106.9873 },
    { id: "mondulkiri", province_name: "Mondulkiri", nameKh: "មណ្ឌលគិរី", city: "Sen Monorom", country: "Cambodia", latitude: 12.4558, longitude: 107.2020 },
    { id: "kratie", province_name: "Kratie", nameKh: "ក្រចេះ", city: "Kratie", country: "Cambodia", latitude: 12.4880, longitude: 106.0288 },
    { id: "pursat", province_name: "Pursat", nameKh: "ពោធិ៍សាត់", city: "Pursat", country: "Cambodia", latitude: 12.5388, longitude: 103.9192 },
    { id: "preah-vihear", province_name: "Preah Vihear", nameKh: "ព្រះវិហារ", city: "Tbaeng Meanchey", country: "Cambodia", latitude: 13.8073, longitude: 104.9805 },
    { id: "banteay-meanchey", province_name: "Banteay Meanchey", nameKh: "បន្ទាយមានជ័យ", city: "Serei Saophoan", country: "Cambodia", latitude: 13.6627, longitude: 102.9737 },
    { id: "oddar-meanchey", province_name: "Oddar Meanchey", nameKh: "ឧត្តរមានជ័យ", city: "Samraong", country: "Cambodia", latitude: 14.1817, longitude: 103.5176 },
    { id: "kep", province_name: "Kep", nameKh: "កែប", city: "Kep", country: "Cambodia", latitude: 10.4829, longitude: 104.3167 },
    { id: "pailin", province_name: "Pailin", nameKh: "ប៉ៃលិន", city: "Pailin", country: "Cambodia", latitude: 12.8490, longitude: 102.6093 },
    { id: "tboung-khmum", province_name: "Tboung Khmum", nameKh: "ត្បូងឃ្មុំ", city: "Suong", country: "Cambodia", latitude: 11.9118, longitude: 105.6582 },
];

export default provinces;